### ISSUE TITLE
Woodrocket-Plugin does not work

### ISSUE THREAD

**Issue by NiciDieNase** [ptom98/PTOM#1]
Looks like the page changed.
I think replacing line 196 of default.py with:
`vidID=util.extract(content, 'file: "http://videos.woodrocket.com/vid/', '.mp4", label: "480p"')
`
fixed it.

**Comment by NiciDieNase** [comment]
I would have opened a proper pull request, but thats kind of pointless with the relevant file beeing in a zip-file.

**Comment by scottydelta** [comment]
I had to replace line 196 with this line to fix it:
```vidID=util.extract(content, '"http://videos.woodrocket.com/vid/', '.mp4"')```

**Comment by ptom98** [comment]
Latest release fixes all WoodRocket issues
