### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by firetrap71** [ptom98/PTOM#14]
JPop not working any fix for it

**Comment by ptom98** [comment]
What issue are you having with it, just tested and appears to be working for me

**Comment by firetrap71** [comment]
Hi Ptom it says dependencies not meet so will not install

Sent from Yahoo Mail on Android 
 
  On Mon, 4 Jun 2018 at 23:02, PTOM<notifications@github.com> wrote:   
What issue are you having with it, just tested and appears to be working for me

**Comment by firetrap71** [comment]
Hi Ptom it says dependencies not meet so will not install

**Comment by ptom98** [comment]
ah, yep i see the issue, will push an update to fix it tomorrow hopefully

**Comment by firetrap71** [comment]
Still no up date ptom
