### ISSUE TITLE
Can't see the any list of the available stream.

### ISSUE THREAD

**Issue by zero7859** [ptom98/PTOM#4]
Hello, I tried to watch any videos on Javstream. when I click any title(such as SDMU-670) on censored it shows no stream. just '....' text for go back. 
![image](https://user-images.githubusercontent.com/31791418/30238203-6fd72038-957d-11e7-91d8-1eb7ce5430ce.jpg)

**Comment by ptom98** [comment]
hmmm, can you upload a copy of the kodi log file and ill take a look for you, when i click on it it loads in quite a few sources. are you using either of the premium link providers or just the free ones? all should have links just trying to think where the problem could be.
![screenshot003](https://user-images.githubusercontent.com/2039110/30238674-45a80348-9543-11e7-8356-c2b5d176b826.png)

**Comment by zero7859** [comment]
I think it happened because of my ISP blocked these streaming sites. when I use your Javpop proxy, it worked but the thumnail and unicode characters are broken.
