### ISSUE TITLE
soggysandwich session id not working.

### ISSUE THREAD

**Issue by hisup** [ptom98/PTOM#7]
Hi I come to tell you that whoever is maintaining soggysandwich, the preset session_id is not working anymore due to crunchyroll probably deleting session data.

**Comment by ptom98** [comment]
thanks the update, just uploaded a fix for this in v0.4
https://github.com/ptom98/PTOM/raw/master/plugin.video.soggysandwich/plugin.video.soggysandwich-0.4.zip
